# This script creates a new tag each time a push is made to the main branch.
# This automatically triggers an update with packagist/composer to reflect latest changes.

name: "Bump version"

on:
  push:
    branches:
      - 7.x

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.65.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: 7.x
          INITIAL_VERSION: 7.0.0
